// Abbreviation all capital letters must be entered here
// AcFD will not work 
const lists = {
'SHRA': 'Moderate Showers of Rain',
'+SHRA': 'Heavy Showers of Rain',
'-SHRA': 'Light Showers of Rain',
'TSRAGS': 'Thunderstorms with Rain and Small Hail',
'RERA': 'Recent Rain',
'VCTS': 'Thunderstorms in the Vicinity',
'FZFG': 'Freezing Fog',
'//': 'Weather not detected due sensor temporarily inoperative - (used in METAR AUTO only)',
'///': 'Cloud is detected (unable to determine TCU/CB) - (used in METAR AUTO only)',
'////': 'Visibility not reported due faulty sensor - (used in METAR AUTO only)',
'/////////': 'Cloud not reported due faulty sensor - (used in METAR AUTO only)',
'-': 'Light',
'+': 'Heavy',
'9999': 'Visibility 10KM or more',
'AAW': 'Aviation Area Winds',
'ABT': 'About',
'ABV': 'Above',
'AC': 'Altocumulus',
'AD QNH': 'Aerodrome QNH forecast',
'AFT': 'After',
'AGL': 'Above ground level',
'AIP': 'Aeronautical Information Publication',
'AIREP': 'Routine air report from aircraft in flight',
'AIREP SPECIAL': 'Special (non-routine) air report from aircraft in flight',
'AMD': 'Amended',
'AMSL': 'Above mean sea level',
'APRX': 'Approximate',
'AS': 'Altostratus',
'AT': 'At',
'ATIS': 'Automatic terminal information service',
'ATS': 'Air traffic services',
'AWIB': 'Aerodrome and weather information broadcast',
'AWS': 'Automatic weather station (produces METAR AUTO)',
'BASE': 'Cloud base',
'BC': 'Patches',
'BDRY': 'Boundary',
'BECMG': 'Becoming',
'BFR': 'Before',
'BKN': 'Broken (5–7 oktas)',
'BL': 'Blowing',
'BLDG': 'Building',
'BLW': 'Below',
'BR': 'Mist (1000–5000 M vis)',
'BTN': 'Between',
'BWR': 'Basic weather report',
'CAT': 'Clear air turbulence',
'CAVOK': 'Cloud and visibility OK',
'CB': 'Cumulonimbus',
'CLD': 'Cloud',
'CLR': 'Clear',
'CNL': 'Cancel',
'CONS': 'Continuous',
'COR': 'Corrected',
'COT': 'At the coast',
'CU': 'Cumulus',
'DP': 'Dew point temperature',
'DR': 'Low drifting',
'DS': 'Duststorm',
'DTRT': 'Deteriorating/deteriorate',
'DU': 'Dust',
'DZ': 'Drizzle',
'EMBD': 'Embedded',
'EST': 'Estimated',
'EXC': 'Except',
'EXTD': 'Extended or extending',
'FC': 'Funnel cloud',
'FCST': 'Forecast',
'FEW': 'Few (1–2 oktas)',
'FG': 'Fog (visibility less than 1000 m)',
'FIR': 'Flight information region',
'FISB': 'Flight information service broadcast',
'FL': 'Flight level',
'FM': 'From',
'FRQ': 'Frequent',
'FU': 'Smoke',
'FZ': 'Freezing',
'FZL': 'Freezing level',
'G': 'Gusts',
'GNZSIGWX': 'Graphical NZ significant weather',
'GR': 'Hail (5 mm or more)',
'GRAFOR': 'Graphical aviation forecast',
'GS': 'Small hail (smaller than 5 mm)',
'GSM': 'Graphical SIGMET Monitor',
'HVY': 'Heavy',
'HZ': 'Haze (visibility less than 5000 m)',
'ICAO': 'International Civil Aviation Organization',
'ICE': 'Icing',
'IFR': 'Instrument flight rules',
'IMC': 'Instrument meteorological conditions',
'IMPR': 'Improving',
'INTSF': 'Intensifying',
'ISOL': 'Isolated',
'KM': 'Kilometres',
'KT': 'Knots',
'LAN': 'Inland',
'LCA': 'Local/locally/location/located',
'LYR': 'Layer',
'M': 'Metres',
'MAX': 'Maximum',
'METAR': 'Aerodrome routine meteorological report',
'METAR AUTO': 'Automatic aerodrome routine meteorological report',
'MI': 'Shallow',
'MOD': 'Moderate',
'MOV': 'Moving',
'MS': 'Minus',
'MT': 'Mountain',
'MTW': 'Mountain waves',
'NC': 'No change',
'NCD': 'No cloud detected below 10,000 ft - (used in METAR AUTO only)',
'NM': 'Nautical miles',
'NOSIG': 'No significant change',
'NS': 'Nimbostratus',
'NSC': 'No significant cloud',
'NSW': 'Nil significant weather',
'NXT': 'Next',
'NZZC': 'New Zealand FIR',
'NZZO': 'Auckland Oceanic FIR',
'OBS': 'Observed',
'OBSC': 'Obscured',
'OCNL': 'Occasional',
'OPMET': 'Operational meteorological information',
'OVC': 'Overcast (8 oktas)',
'PIREP': 'Pilot report (AIREP)',
'PL': 'Ice pellets',
'PO': 'Dust/sand whirls',
'PR': 'Partial',
'PROB': 'Probability',
'PS': 'Plus',
'PSN': 'Position',
'Q': 'QNH',
'QNH': 'Altimeter sub-scale setting',
'R': 'Runway',
'RA': 'Rain',
'RDOACT': 'Radioactive',
'RE': 'Recent',
'RMK': 'Remark',
'ROFOR': 'Route forecast',
'RVR': 'Runway visual range',
'SA': 'Sand',
'SC': 'Stratocumulus',
'SCT': 'Scattered (3–4 oktas)',
'SECT': 'Sector',
'SEV': 'Severe',
'SFC': 'Surface',
'SG': 'Snow grains',
'SH': 'Shower',
'SIG': 'Significant',
'SIGMET': 'Significant meteorological information',
'SIGWX': 'Significant weather forecast',
'SKC': 'Sky clear (no cloud at all)',
'SN': 'Snow',
'SPECI': 'Aerodrome special meteorological report',
'SQ': 'Squall',
'SQL': 'Squall line',
'SS': 'Sandstorm (MET) or Sunset in Flight Planning',
'ST': 'Stratus | or St = Stabilised',
'STNR': 'Stationary',
'T': 'Temperature, in degrees Celsius (MET) or True (bearing, heading, track) in Flight Planning',
'TAF': 'Aerodrome forecast',
'TC': 'Tropical cyclone',
'TCU': 'Towering cumulus',
'TEMPO': 'Temporarily',
'TL': 'Till',
'TREND': 'Trend forecast',
'TS': 'Thunderstorm',
'TURB': 'Turbulence',
'UP': 'Unidentified precipitation',
'UTC': 'Coordinated Universal Time',
'V': 'Variations from mean wind direction',
'VA': 'Volcanic ash',
'VAA': 'Volcanic Ash Advisory',
'VAAC': 'Volcanic Ash Advisory Centre',
'VAG': 'Volcanic Ash Graphic',
'VAL': 'In valleys', 
'VC': 'Vicinity of the aerodrome (followed by FG=fog, FC=funnel cloud, SH=showers, PO=dust/sand whirls, BLDU=blowing dust, BLSA=blowing sand or BLSN=blowing snow, e.g. VCFG=vicinity fog)',
'VCY': 'Vicinity',
'VFR': 'Visual flight rules',
'VIS': 'Visibility',
'VMC': 'Visual meteorological conditions',
'VRB': 'Variable',
'VV': 'Vertical visibility',
'WI': 'Within',
'WKN': 'Weakening',
'WDSPR': 'Widespread',
'WS': 'Windshear',
'WX': 'Weather',
'Z': 'Coordinated Universal Time',
'A': 'Amber',
'A/A': 'Air-to-air',
'A/G': 'Air to ground',
'AAA': '(or AAB, AAC ... etc in sequence) Amended meteorological message',
'AAD': 'Assigned altitude deviation',
'AAL': 'Above aerodrome level',
'ABI': 'Advance boundary information',
'ABM': 'Abeam',
'ABN': 'Aerodrome beacon',
'ACARS': 'Aircraft communication addressing and reporting system (pronounced "AY-CARS")',
'ACAS': 'Airborne collision avoidance system (pronounced "AY-CASS")',
'ACC': 'Area control centre or area control',
'ACCID': 'Notification of an aircraft accident',
'ACFT': 'Aircraft',
'ACK': 'Acknowledge',
'ACL': 'Altimeter check location',
'ACN': 'Aircraft classification number',
'ACNZ': 'Airways Corporation of New Zealand Limited',
'ACPT': 'Accept or accepted',
'ACT': 'Active or activated or activity',
'AD': 'Airworthiness Directive',
'ADA': 'Advisory area',
'ADC': 'Aerodrome chart',
'ADDN': '	Addition or additional',
'ADEP': 'Aerodrome of Departure',
'ADES': 'Aerodrome of Destination',
'ADF': 'Automatic direction-finding equipment or automatic direction-finder',
'ADIZ': 'Air defence identification zone (pronounced "AY-DIZ")',
'ADJ': 'Adjacent',
'ADO': 'Aerodrome office (specify service)',
'ADR': 'Advisory route',
'ADS-B': 'Automatic Dependent Surveillance - Broadcast',
'ADS-C': 'Automatic Dependent Surveillance - Contract',
'ADSU': 'Automatic dependent surveillance unit',
'ADVS': 'Advisory service',
'ADZ': 'Advise',
'AES': 'Aircraft earth station',
'AFFF': 'Aqueous film forming foam',
'AFIL': 'Flight plan filed in the air',
'AFIS': 'Aerodrome flight information service',
'AFM': 'Yes or affirm or affirmative or that is correct',
'AFRU': '	Aerodrome frequency response unit',
'AFS': 'Aeronautical fixed service',
'AFT': 'After ... (time or place)',
'AFTN': 'Aeronautical fixed telecommunications network',
'AGA': 'Aerodromes, air routes and ground aids',
'AGN': 'Again',
'AGNIS': 'Azimuth guidance for nose-in stands',
'AIC': '	Aeronautical information circular',
'AIDC': 'Air traffic services inter-facility data communication',
'AIP': 'Aeronautical information publication',
'AIPNZ': 'Aeronautical information publication of New Zealand',
'AIRAC': 'Aeronautical information regulation and control',
'AIRMET': 'Information concerning enroute weather phenomena which may affect the safety of low-level aircraft operations',
'AIS': 'Aeronautical information services',
'ALA': 'Alighting area',
'ALERFA': 'Alert phase',
'ALRS': 'Alerting service',
'ALS': 'Approach lighting system',
'ALT': 'Altitude',
'ALTN': 'Alternate (aerodrome)',
'AMA': 'Area minimum altitude',
'AMD': 'Amend',
'AMDT': 'Amendment (AIP Amendment)',
'AMS': 'Aeronautical mobile service',
'AMSS': 'Aeronautical mobile satellite service',
'ANC': 'Aeronautical chart 1:500 000 (followed by name/title)',
'ANS': 'Answer',
'AOC': 'Aerodrome obstacle chart (followed by type and name/title)',
'AP': 'Airport',
'APAPI': 'Abbreviated precision approach path indicator (pronounced "AY-PAPI")',
'APCH': 'Approach',
'APDC': 'Aircraft parking/docking chart (followed by name/title)',
'APIS': 'Aircraft parking information system',
'APN': 'Apron',
'APP': 'Approach control office or Approach control or Approach control service',
'APR': 'April',
'APRX': 'Approximate or approximately',
'APSG': 'After passing',
'APV': 'Approve or approved or approval',
'ARC': 'Aerodrome reference code',
'ARFL': 'Aerodrome reference field length',
'ARFOR': 'Area forecast (in aeronautical meteorological code)',
'ARNG': 'Arrange',
'ARO': 'Air traffic services reporting office',
'ARP': 'Aerodrome reference point',
'ARQ': 'Automatic error correction',
'ARR': 'Arrive or arrival',
'ARST': 'Arresting [specify (part of) aircraft arresting equipment]',
'AS': 'Altostratus',
'ASC': 'Ascend to or Ascending to',
'ASDA': '	Accelerate-stop distance available',
'ASE': 'Altimetry system error',
'ASPH': 'Asphalt',
'AT-VASIS': 'Abbreviated T visual approach slope indicator system (pronounced "AY-TEE-VASIS")',
'AT...': 'At (followed by time at which weather change is forecast to occur)',
'ATA': 'Actual time of arrival',
'ATC': 'Air traffic control (in general)',
'ATCC': 'Air Traffic Control Centre',
'ATD': 'Actual time of departure or Along Track Distance',
'ATFM': 'Air traffic flow management',
'ATM': 'Air traffic management',
'ATN': 'Aeronautical telecommunication network',
'ATP': 'At ... (time or place)',
'ATSC': 'Air Traffic Services Centre',
'ATTN': 'Attention',
'AUG': 'August',
'August': 'Authorised or Authorisation',
'AUW': 'All up weight',
'AUX': 'Auxiliary',
'AVASIS': 'Abbreviated visual approach slope indicator system (pronounced "AY-VASIS")',
'AVBL': 'Available or Availability',
'AVG': 'Average',
'AVGAS': 'Aviation gasoline',
'AWTA': 'Advise at what time able',
'AWY': 'Airway',
'AZM': 'Azimuth',
'B': 'Bitumen',
'BA': 'Braking action',
'BCFG': 'Fog patches',
'BCN': 'Beacon (Aeronautical ground light)',
'BCST': 'Broadcast',
'BI': 'Bi-directional',
'BL': 'Blowing (followed by DU=dust, SA=sand or SN=snow)',
'BLO': 'Below clouds',
'BOMB': 'Bombing',
'BRF': 'Short (used to indicate the type of approach desired or required)',
'BRG': 'Bearing',
'BRKG': 'Braking',
'BRNAV': 'Basic area navigation (pronounced "BEE-AR-NAV")',
'BS': 'Commercial broadcasting station',
'BTL': 'Between layers',
'C': 'Degrees Celsius (Centigrade)',
'CAA': 'NZ Civil Aviation Authority',
'CAM': 'Collaborative Arrival Manager',
'CAR': 'NZ Civil Aviation Rules',
'CC': 'Cirrocumulus',
'CCA': '(or CCB, CCC ... etc in sequence) Corrected meteorological message',
'CD': 'Candela(s)',
'CF': 'Course Fix (used with GNSS approaches - often equivalent to IF)',
'CFM': 'Confirm or I confirm',
'CFZ': 'Common Frequency Zone',
'CGL': 'Circling guidance light(s)',
'CH': 'Channel',
'CI': 'Cirrus',
'CIDIN': 'Common ICAO interchange network',
'CIT': 'Near or over large town(s)',
'CIV': 'Civil',
'CK': 'Check',
'CL': 'Centre line',
'CLA': 'Clear type of ice formation',
'CLBR': 'Calibration',
'CLG': 'Calling',
'CLIAS': 'Climbing indicated speed',
'CLR': 'Cleared or Cleared to ... or Clearance',
'CLSD': 'Close or Closed or Closing',
'CM': 'Centimetre',
'CMB': 'Climb to or Climbing to',
'CMPL': 'Completion or Completed or Complete',
'CMSD': 'Commissioned',
'CNL': 'Cancel or Cancelled',
'CNS': 'Communications, navigation and surveillance',
'COL': 'Column',
'COM': 'Communications',
'CONC': 'Concrete',
'COND': 'Condition(s)',
'CONS': 'Continuous',
'CONST': 'Construction or Constructed',
'CONT': 'Continue or Continued',
'COOR': 'Coordinate or Coordination',
'COORD': 'Coordinates',
'COP': 'Change-over point',
'COR': 'Correct or Corrected',
'COV': 'Cover or Covered or Covering',
'CPDLC': 'Controller-pilot data link communications',
'CRC': 'Cyclic redundancy check',
'CRZ': 'Cruise',
'CS': 'Cirrostratus',
'CTA': 'Control area',
'CTAM': 'Climb to and maintain',
'CTC': 'Contact',
'CTL': 'Control',
'CTN': 'Caution',
'CTOT': 'Calculated Time of Departure (pronounced "SEE TOT")',
'CTR': 'Control zone',
'CUF': 'Cumuliform',
'CUST': 'Customs',
'CVFR': 'Controlled VFR',
'CVR': 'Cockpit voice recorder',
'CW': 'Continuous wave',
'CWY': 'Clearway',
'D': 'Downward (tendency in RVR during previous 10 minutes)',
'D-ATIS': 'Data link automatic terminal information service (pronounced "DEE-ATIS")',
'D-VOLMET': 'Data link VOLMET',
'D...': 'Danger area (followed by identification)',
'DA': 'Decision altitude',
'DCA': 'Director of Civil Aviation',
'DCD': 'Double channel duplex',
'DCKG': 'Docking',
'DCL': 'Digital Clearance Delivery',
'DCMSD': 'Decommissioned',
'DCPC': 'Direct controller-pilot communications',
'DCS': 'Double channel simplex',
'DCT': 'Direct (in relation to flight plan clearances and type of approach)',
'DEC': 'December',
'DEG': 'Degrees',
'DEP': 'Depart or Departure',
'DES': 'Descend to or Descending to',
'DEST': 'Destination',
'DETRESFA': 'Distress phase',
'DEV': 'Deviation or Deviating',
'DF': 'Direction finding',
'DFDR': 'Digital flight data recorder',
'DFTI': 'Distance from touchdown indicator',
'DH': 'Decision height',
'DIF': 'Diffuse',
'DISP': 'Displaced',
'DIST': 'Distance',
'DIV': 'Divert or Diverting or Diversion',
'DLA': 'Delay or Delayed',
'DLIC': 'Data link initiation capability',
'DLV': 'Delivery',
'DLY': 'Daily',
'DME': 'Distance measuring equipment',
'DNG': 'Danger or Dangerous',
'DOM': 'Domestic',
'DPT': 'Depth',
'DR': 'Dead reckoning',
'DR...': 'Low drifting (followed by DU=dust, SA=sand or SN=snow)',
'DRG': 'During',
'DSB': 'Double sideband',
'DTAM': 'Descend to and maintain',
'DTG': 'Date time group',
'DTHR': 'Displaced runway threshold',
'DTRT': 'Deteriorate or Deteriorating',
'DTW': 'Dual tandem wheels',
'DUC': 'Dense upper cloud',
'DUR': 'Duration',
'DVOR': 'Doppler VOR',
'DW': 'Dual wheels',
'E': 'East or Eastern longitude',
'EAT': 'Expected approach time',
'EB': 'Eastbound',
'ECT': 'Evening civil twilight',
'EET': 'Estimated elapsed time',
'EFC': 'Expect further clearance',
'EGPWS': 'Enhanced ground proximity warning system',
'EHF': 'Extremely high frequency [30 000 to 300 000 MHz]',
'ELBA': 'Emergency locator beacon - aircraft',
'ELEV': 'Elevation',
'ELR': 'Extra long range',
'ELT': 'Emergency locator transmitter',
'EM': 'Emission',
'EMBD': 'Embedded in a layer (to indicate cumulonimbus embedded in layers of other clouds)',
'EMERG': 'Emergency',
'END': 'Stop-end (related to RVR)',
'ENDC': 'Endurance',
'ENE': 'East north-east',
'ENG': 'Engine',
'ENR': 'Enroute',
'ENRC': 'Enroute chart (followed by name/title)',
'EOBT': 'Estimated off-blocks time',
'EOL': 'Effective operational length',
'EPIRB': 'Emergency position indicating radio beacon',
'EQPT': 'Equipment',
'ER': 'Here ... or Herewith',
'ESE': 'East south-east',
'ESWL': 'Equivalent single wheel load',
'ETA': 'Estimated time of arrival or estimating arrival',
'ETD': 'Estimated time of departure or estimating departure',
'ETO': 'Estimated time over a significant point',
'ETOPS': 'Extended-range twin-engine operations',
'EV': 'Every',
'EXC': 'Except',
'EXER': 'Exercises or Exercising or to Exercise',
'EXP': 'Expect or Expected or Expecting',
'EXTD': 'Extend or Extending',
'F': 'Fixed',
'FAC': 'Facilities', 
'FAF': 'Final approach fix', 
'FAL': 'Facilitation of international air transport', 
'FAP': 'Final approach point', 
'FATO': 'Final approach and take-off area', 
'FAX': 'Facsimile transmission', 
'FBL': 'Light (used to indicate the intensity of weather phenomena, interference or static reports, e.g. FBL RA=light rain)', 
'FC': 'Funnel cloud', 
'FCST': 'Forecast', 
'FCT': 'Friction coefficient', 
'FDPS': 'Flight data processing system', 
'FEB': 'February', 
'FIC': 'Flight information centre', 
'FIS': 'Flight information service', 
'FISA': 'Automated flight information service', 
'FISB': 'Flight information service broadcasts', 
'FLD': 'Field', 
'FLG': 'Flashing', 
'FLR': 'Flares', 
'FLT': 'Flight', 
'FLTCK': 'Flight check', 
'FLUC': 'Fluctuating or Fluctuation or Fluctuated', 
'FLW': 'Follow(s) or Following', 
'FLY': 'Fly or Flying', 
'FM...': 'From (followed by time weather change is forecast to begin)', 
'FMS': 'Flight management system', 
'FMU': 'Flow management unit', 
'FNA': 'Final approach', 
'FPD': 'Flight plan designator', 
'FPM': 'Feet per minute', 
'FPR': 'Flight plan route', 
'FR': 'Fuel remaining', 
'FREQ': 'Frequency', 
'FRI': 'Friday', 
'FRNG': 'Firing', 
'FRONT': 'Front (relating to weather)', 
'FS': 'Flight service', 
'FSL': 'Full stop landing', 
'FSS': 'Flight service station', 
'FST': 'First', 
'FZDZ': 'Freezing drizzle', 
'FZFG': 'Freezing fog', 
'FZRA': 'Freezing rain', 
'FT': 'Feet (dimensional unit)', 
'G': 'Indicator for variations from the mean wind speed (gusts) (used in the METAR/SPECI and TAF code forms)',
'G/A': 'Ground-to-air', 
'G/A/G': 'Ground-to-air and air-to-ground', 
'GA': 'General aviation', 
'GAA': 'General aviation area (applies to airspace)', 
'GAMET': 'Area forecast for low-level flights', 
'GEN': 'General', 
'GEO': 'Geographic or true', 
'GES': 'Ground earth station', 
'GG': 'Whole hours UTC', 
'GLD': 'Glider', 
'GLONASS': 'Global orbiting navigation satellite system (pronounced "GLO-NASS")', 
'GMC': 'Ground movement chart (followed by name/title)', 
'GND': 'Ground', 
'GNDCK': 'Ground check', 
'GNSS': 'Global navigation satellite system', 
'GNZSIGWX': 'Graphical NZ Significant Weather (chart)', 
'GP': 'Glide path', 
'GPS': 'Global Positioning System', 
'GPWS': 'Ground proximity warning system', 
'GRASS': 'Grass landing area', 
'GRIB': 'Processed meteorological data in the form of grid values (in aeronautical meteorological code)', 
'GS': 'Ground speed', 
'GSM': 'Graphical SIGMET Monitor (chart)', 
'GUND': 'Geoid undulation', 
'GP': 'Group', 
'GR': 'Grass', 
'GR(F)': 'Firm grass', 
'GR(S)': 'Soft grass', 
'H': 'High pressure area or the centre of high pressure', 
'H,H': 'Depth of flexible pavement', 
'H , H': 'Depth of flexible pavement',
'H24': 'Continuous day and night service', 
'HAPI': 'Helicopter approach path indicator', 
'HBN': 'Hazard beacon', 
'HDF': 'High frequency direction-finding station', 
'HDG': 'Heading', 
'HEL': 'Helicopter', 
'HEL-H': 'Heavy helicopter (radius of action in excess of 100 NM)', 
'HEL-L': 'Light helicopter (radius of action of 50 NM and capacity for evacuating one person)', 
'HEL-M': 'Medium helicopter (radius of action of 50 to 100 NM)', 
'HF': 'High frequency [3 000 to 30 000 kHz]', 
'HGT': 'Height or Height above', 
'HJ': 'Sunrise to sunset', 
'HLDG': 'Holding', 
'HN': 'Sunset to sunrise', 
'HO': 'Service available to meet operational requirements', 
'HOL': 'Holiday', 
'HOSP': 'Hospital aircraft', 
'HR': 'Hours', 
'HS': 'Service available during hours of scheduled operations', 
'HUMS': 'Health and usage monitoring system', 
'HURCN': 'Hurricane', 
'HVDF': 'High and very high frequency direction-finding stations (at the same location)', 
'HX': 'No specific working hours', 
'HYR': 'Higher', 
'HPA': 'Hectopascal',
'IAC': 'Instrument approach chart', 
'IAF': 'Initial approach fix', 
'IAO': 'In and out of clouds', 
'IAR': 'Intersection of air routes', 
'IAS': 'Indicated air speed', 
'IBN': 'Identification beacon', 
'IC': 'Ice crystals (very small ice crystals in suspension - also known as diamond dust)', 
'ICAO': 'International Civil Aviation Organisation', 
'ICE': 'Icing', 
'ID': 'Identifier or Identify', 
'IDENT': 'Identification', 
'IDF': 'Initial Departure Fix', 
'IF': 'Intermediate approach fix', 
'IFF': 'Identification friend/foe', 
'IFIS': 'Internet Flight Information Service', 
'IFR': 'Instrument flight rules', 
'IFT': 'Instrument Flight Test (Initial Issue)', 
'IGA': 'International general aviation', 
'ILS': 'Instrument landing system', 
'IM': 'Inner marker', 
'IMC': 'Instrument meteorological conditions', 
'IMG': 'Immigration', 
'IMPR': 'Improve or improving', 
'IMT': 'Immediate or Immediately', 
'INA': 'Initial approach', 
'INBD': 'Inbound', 
'INC': 'In cloud', 
'INCERFA': 'Uncertainty phase', 
'INFO': 'Information', 
'INOP': 'Inoperative', 
'INP': 'If not possible', 
'INPR': 'In progress', 
'INS': 'Inertial navigation system', 
'INSTL': 'Install or Installed or Installation', 
'INSTR': 'Instrument', 
'INT': 'Intersection', 
'INTL': 'International', 
'INTRG': 'Interrogator', 
'INTRP': 'Interrupt or Interruption or Interrupted', 
'INTSF': 'Intensify or Intensifying', 
'INTST': 'Intensity', 
'IR': 'Ice on runway', 
'ISA': 'International standard atmosphere', 
'ISB': 'Independent sideband', 
'ISOL': 'Isolated',
'JAN': 'January', 
'JTST': 'Jet stream', 
'JUL': 'July', 
'JUN': 'June', 
'KHZ': 'Kilohertz', 
'KPA': 'KiloPascal/s', 
'KW': 'Kilowatt/s', 
'KG': 'Kilogram/s', 
'KMH': 'Kilometres per hour', 
'L': 'Low pressure area or the centre of low pressure', 
'L,L': 'Radius of relative stiffness of rigid pavement', 
'LAT': 'Latitude', 
'LDA': 'Landing distance available', 
'LDAH': 'Landing distance available, helicopter', 
'LDG': 'Landing', 
'LDI': 'Landing direction indicator', 
'LEN': 'Length', 
'LF': 'Low frequency [30 to 300 kHz]', 
'LFZ': 'Low flying zone', 
'LGT': 'Light or Lighting',
'LGTD': 'Lighted', 
'LIH': 'Light intensity high', 
'LIL': 'Light intensity low', 
'LIM': 'Light intensity medium', 
'LL': 'Lower limit(s)', 
'LLCA': 'Lower limit of controlled airspace', 
'LM': 'Locator, middle', 
'LMT': 'Local mean time', 
'LNAV': 'Lateral navigation', 
'LNG': 'Long (used to indicate the type of approach desired or required)', 
'LO': 'Locator, outer', 
'LOA': 'Length overall', 
'LOC': 'Localiser', 
'LONG': 'Longitude', 
'LORAN': 'Long range air navigation system', 
'LRG': 'Long range', 
'LRNS': 'Long range navigation system', 
'LTD': 'Limited', 
'LTT': 'Landline teletypewriter', 
'LV': 'Light and variable (relating to wind)', 
'LVE': 'Leave or Leaving', 
'LVL': 'Level', 
'LVP': 'Low Visibility Procedures', 
'M': 'Indicator for minimum value of runway visual range (used in the METAR/SPECI code forms)', 
'MAA': 'Maximum authorised altitude', 
'MAG': 'Magnetic', 
'MAINT': 'Maintenance', 
'MAP': 'Aeronautical maps and charts', 
'MAPt': 'Missed approach point', 
'MAR': 'At sea', 
'MAUW': 'Maximum all-up weight', 
'MAY': 'May', 
'MBZ': 'Mandatory Broadcast Zone', 
'MCA': 'Minimum crossing altitude', 
'MCT': 'Morning civil twilight', 
'MCTOW': 'Maximum certificated take-off weight', 
'MCW': 'Modulated continuous wave', 
'MDA': 'Minimum descent altitude', 
'MDF': 'Medium frequency direction-finding station', 
'MDH': 'Minimum descent height', 
'MEA': 'Minimum enroute altitude', 
'MED': 'Medical', 
'MEHT': 'Minimum eye height over threshold (for visual approach slope indicator systems)', 
'MEL': 'Minimum equipment list', 
'MET': 'Meteorological or Meteorology', 
'METREPORT': 'Local routine meteorological report (in abbreviated plain language)', 
'METAR': 'Aviation routine weather report (in aeronautical meteorological code)', 
'MF': 'Medium frequency [300 to 3 000 kHz]', 
'MFA': 'Minimum flight altitude', 
'MHDF': 'Medium and high frequency direction-finding stations (at the same location)', 
'MHVDF': 'Medium, High and Very High frequency direction-finding stations (at the same location)', 
'MHz': 'Megahertz', 
'MID': 'Mid-point (related to RVR)', 
'MIFG': 'Shallow fog', 
'MIL': 'Military', 
'MKR': 'Marker radio beacon', 
'MLAT': 'Multilateration', 
'MLFZ': 'Military low flying zone', 
'MLS': 'Microwave landing system', 
'MM': 'Middle marker', 
'MNM': 'Minimum', 
'MNPS': 'Minimum navigation performance specifications', 
'MNT': 'Monitor or Monitoring or Monitored', 
'MNTN': 'Maintain', 
'MOA': 'Military operating area', 
'MOC': 'Minimum obstacle clearance (required)', 
'MOD': 'Moderate (used to indicate the intensity of weather phenomena, interference or static reports, e.g. MOD RA=moderate rain.)', 
'MON': 'Monday', 
'MOPS': 'Minimum operational performance standards', 
'MOV': 'Move or Moving or Movement', 
'MPS': 'Metres per second', 
'MRA': 'Minimum reception altitudes', 
'MRG': 'Medium range', 
'MRP': 'ATS/MET reporting point', 
'MSA': 'Minimum safe altitude (non-ICAO usage, based on Civil Aviation Rule 91.423)', 
'MSA25NM': 'Minimum sector altitude (ICAO definition based on 25 NM obstacle clearance)', 
'MSAW': 'Minimum safe altitude warning', 
'MSG': 'Message', 
'MSL': 'Mean sea level', 
'MSSR': 'Monopulse secondary surveillance radar', 
'MTOW': 'Maximum take-off weight', 
'MTP': 'Maximum tyre pressure', 
'MTU': 'Metric units', 
'MTW': 'Mountain waves',
'MVDF': 'Medium and very high frequency direction-finding stations (at the same location)', 
'MWARA': 'Major world air route area', 
'MWO': 'Meteorological watch office', 
'MX': 'Mixed type of ice formation (white and clear)', 
'MIN': 'Minute/s',
'N': 'North or Northern latitude', 
'NA': 'Not authorised', 
'NASC': 'National AIS system centre', 
'NAV': 'Navigation', 
'NB': 'Northbound', 
'NBFR': 'Not before', 
'NDB': 'Non-directional radio beacon', 
'NDT': 'Non-destructive testing', 
'NE': 'North-east', 
'NEB': 'North-eastbound', 
'NEG': 'No or Negative or Permission not granted or That is not correct', 
'NGT': 'Night', 
'NIL': 'None or I have nothing to send you', 
'NML': 'Normal', 
'NNE': 'North north-east', 
'NNW': 'North north-west', 
'NOF': 'International NOTAM office', 
'NORDO': 'Non-radio equipped', 
'NOTAM': 'Notice to airmen - A notice containing information concerning the establishment, condition or change in any aeronautical facility, service, procedure or hazard, the timely knowledge of which is essential to personnel concerned with flight operations', 
'NOV': 'November', 
'NOZ': 'Normal operating zone', 
'NPA': 'Non-precision approach', 
'NR': 'Number', 
'NRCC': 'National Rescue Coordination Centre', 
'NRH': 'No reply heard', 
'NTL': 'National', 
'NTZ': 'No transgression zone', 
'NU': 'Not usable', 
'NW': 'North-west', 
'NWB': 'North-westbound', 
'NWFC': 'National weather forecasting centre', 
'NXT': 'Next', 
'NZ': 'New Zealand', 
'NZA...': 'Controlled Airspace (followed by identification)', 
'NZA': 'Controlled Airspace', 
'NZB...': 'Mandatory Broadcast Zone (followed by identification)',
'NZB': 'Mandatory Broadcast Zone',
'NZC...': '(Common Frequency Zone (followed by identification)',
'NZC': 'Common Frequency Zone',  
'NZD...': 'Danger area (followed by identification)', 
'NZD': 'Danger area',
'NZDT': 'New Zealand daylight time (UTC plus 13 hours)', 
'NZG...': 'General Aviation Area (followed by identification)', 
'NZG': 'General Aviation Area',
'NZL...': 'Low Flying Zone (followed by identification)', 
'NZL': 'Low Flying Zone',
'NZM...': 'Military Operating Area (followed by identification)', 
'NZM': 'Military Operating Area',
'NZMS...': 'New Zealand Mapping Service map series number (followed by identification)', 
'NZMS': 'New Zealand Mapping Service map series number',
'NZP...': 'Parachute Landing Area (followed by identification)', 
'NZP': 'Parachute Landing Area',
'NZR...': 'Restricted area (followed by identification)', 
'NZR': 'Restricted area',
'NZST': 'New Zealand standard time (UTC plus 12 hours)', 
'NZT...': 'VFR Transit Lane (followed by identification)', 
'NZT': 'VFR Transit Lane',
'NZV...': 'Volcanic Hazard Zone (followed by identification)', 
'NZV': 'Volcanic Hazard Zone',
'O/R': 'On request', 
'OAC': 'Oceanic area control centre', 
'OAS': 'Obstacle assessment surface', 
'OBS': 'Observe or Observed or Observation', 
'OBSC': 'Obscure or Obscured or Obscuring', 
'OBST': 'Obstacle', 
'OCA': 'Oceanic control area', 
'OCC': 'Occulting (light)', 
'OCH': 'Obstacle clearance height', 
'OCNL': 'Occasional or Occasionally', 
'OCR': 'Oceanic Radar Sector', 
'OCS': 'Obstacle clearance surface', 
'OCT': 'October', 
'OEI': 'One engine inoperative', 
'OFIS': 'Operational flight information service broadcasts', 
'OFZ': 'Obstacle free zone', 
'OHD': 'Overhead', 
'OKTA': 'Eighths of sky cover', 
'OL': 'Overland', 
'OLDI': 'On-line data interchange', 
'OM': 'Outer marker', 
'OMNI': 'Omni-directional', 
'OPA': 'Opaque, white type of ice formation', 
'OPC': 'The control indicated is operational control', 
'OPMET': 'Operational meteorological (information)', 
'OPN': 'Open or Opening or Opened', 
'OPR': 'Operator or Operate or Operative or Operating or Operational', 
'OPS': 'Operations', 
'ORD': 'Indication of an order', 
'OSV': 'Ocean station vehicle', 
'OTLK': 'Outlook (used in SIGMET messages for volcanic ash and tropical cyclones)', 
'OTP': 'On top', 
'OUBD': 'Outbound', 
'OVC': 'Overcast', 
'OW': 'Over water', 
'P': 'Indicator for maximum value of wind speed or runway visual range (used in the METAR/SPECI and TAF code forms)',
'P...': 'Prohibited area (followed by identification)',
'PAL': 'Pilot activated lighting',
'PALS': 'Precision approach lighting system (specify category)',
'PANS': 'Procedures for air navigation services',
'PAPI': 'Precision approach path indicator',
'PAR': 'Precision approach radar',
'PARL': 'Parallel',
'PATC': 'Precision approach terrain chart (followed by name/title)',
'PAX': 'Passenger(s)',
'PBN': 'Performance-based navigation',
'PCD': 'Proceed or Proceeding',
'PCL': 'Pilot-controlled lighting',
'PCN': 'Pavement classification number',
'PDC': 'Pre-departure clearance',
'PDG': 'Procedure design gradient',
'PER': 'Performance',
'PERM':'Permanent',
'PIB': 'Pre-flight information bulletin',
'PIREP': 'A Pilot Report or PIREP is a report of the actual weather conditions as encountered by an aircraft in flight.',
'PJE': 'Parachute jumping exercise',
'PLA': 'Parachute landing area',
'PLN': 'Flight plan',
'PLVL': 'Present level',
'PN': 'Prior notice required',
'PNR': 'Point of no return',
'POB': 'Persons on board',
'POSS': 'Possible',
'PPI': 'Plan position indicator',
'PPR': 'Prior permission required',
'PPSN': 'Present position',
'PRFG': 'Aerodrome partially covered by fog',
'PRI': 'Primary',
'PRKG': 'Parking',
'PROC': 'Procedure',
'PROV': 'Provisional',
'PSG': 'Passing',
'PSR': 'Primary surveillance radar',
'PSYS': 'Pressure system',
'PTN': 'Procedure turn',
'PTS': 'Polar track structure',
'PVT': 'Private',
'PWR': 'Power',
'QDM': 'Magnetic heading (zero wind)', 
'QDR': 'Magnetic heading', 
'QFE': 'Atmospheric pressure at aerodrome level (or at runway threshold)', 
'QFU': 'Magnetic orientation of runway', 
'QTE': 'True bearing', 
'QUAD': 'Quadrant', 
'R...': 'VOR Radial, e.g. R345',
'RAFC': 'Regional area forecast centre',
'RAG': 'Ragged',
'RAI': 'Runway alignment indicator',
'RAIM': 'Receiver autonomous integrity monitoring',
'RASC': 'Regional AIS system centre',
'RB': 'Rescue boat',
'RCA': 'Reach cruising altitude',
'RCC': 'Rescue Coordination Centre',
'RCH': 'Reach or Reaching',
'RCL': 'Runway centre line',
'RCLL': 'Runway centre line light(s)',
'RCLR': 'Recleared',
'RDARA': 'Regional and Domestic air route area',
'RDH': 'Reference datum height',
'RDL': 'Radial',
'RDO': 'Radio',
'RDPS': 'Radar data processing system',
'RE': 'Rolled earth',
'RE...':  'Recent (used to qualify weather phenomena, e.g. RERA=recent rain)',
'REC': 'Receive or Receiver',
'REDL': 'Runway edge light(s)',
'REF': 'Reference to ... or Refer to ...',
'REG': 'Registration',
'REIL': 'Runway end identifier lights',
'RENL': 'Runway end light(s)',
'REP': 'Report or Reporting or Reporting point',
'REQ': 'Request or Requested',
'RERTE': 'Re-route',
'RESA': 'Runway end safety area',
'RESTR': 'Restriction(s)',
'RF': 'Constant radius arc to a fix',
'RFDPS': 'Radar and flight data processing system',
'RFS': 'Rescue fire service',
'RG': 'Range (lights)',
'RHC': 'Right-hand circuit',
'RIF': 'Re-clearance in flight',
'RITE':'Right (direction of turn)',
'RL': 'Reporting leaving',
'RLA': 'Relay to',
'RLCE': 'Request level change enroute',
'RLLS': 'Runway lead-in lighting system',
'RLNA': 'Request level not available',
'RMK': 'Remark(s)',
'RNAV': 'Area navigation (pronounced "AR-NAV")',
'RNG': 'Radio range',
'RNP': 'Required navigation performance',
'RNZAF': 'Royal New Zealand Air Force',
'ROBEX': 'Routine OPMET Bulletin Exchange (scheme)',
'ROC': 'Rate of climb',
'ROD': 'Rate of descent',
'ROFOR': 'Route forecast',
'ROL': 'Route operating limitation',
'RON': 'Receiving only',
'RPA': 'Remotely piloted aircraft',
'RPAS': 'Remotely piloted aircraft system',
'RPI': 'Radar position indicator',
'RPL': 'Repetitive flight plan',
'RPLC': 'Replace or Replaced',
'RPM':  'Revolutions per minute',
'RPS': 'Radar position symbol',
'RQMNTS': 'Requirements',
'RR': 'Report reaching',
'RSC': 'Rescue sub-centre',
'RSCD': 'Runway surface condition',
'RSP': 'Responder beacon',
'RSR': 'Enroute surveillance radar',
'RTE': 'Route',
'RTF': 'Radio telephone',
'RTG': 'Radiotelegraph',
'RTHL': 'Runway threshold light(s)',
'RTN':  'Return or Returned or Returning',
'RTODAH': 'Rejected take-off distance available, helicopter',
'RTS': 'Return to service',
'RTT': 'Radio teletypewriter',
'RTZL': 'Runway touchdown zone light(s)',
'RUT': 'Standard regional route transmitting frequencies',
'RV': 'Rescue vessel',
'RVSM': 'Reduced vertical separation minimum',
'RWY': 'Runway',
'S': 'South or Southern latitude | Second/s',
'SALS': 'Simple approach lighting system',
'SAN': 'Sanitary',
'SAP': 'As soon as possible',
'SAR': 'Search and rescue',
'SARPS': 'Standards and recommended practices [ICAO]',
'SAT': 'Saturday',
'SATCOM': 'Satellite communication',
'SB': 'Southbound',
'SDBY': 'Standby',
'SE': 'South-east',
'SEB': 'South-eastbound',
'SEC': 'Seconds',
'SECN': 'Section',
'SECT': 'Sector',
'SEIFR': 'Single-engined IFR',
'SELCAL': 'Selective calling system',
'SEP': 'September',
'SER': 'Service or Servicing or Serviced',
'SEV': 'Severe (used to qualify icing and turbulence reports)',
'SGL': 'Signal',
'SH...':  'Showers (followed by RA=rain, SN=snow, PL=icepellets, GR=hail, GS=small hail and/or ice pellets or combinations thereof, e.g. SHRASN=showers of rain and snow)',
'SHF': 'Super high frequency [3 000 to 30 000 MHz]',
'SID': 'Standard instrument departure',
'SIF': 'Selective identification feature',
'SIMUL': 'Simultaneous or Simultaneously',
'SIWL': 'Single isolated wheel load',
'SKED': 'Schedule or Scheduled',
'SLP': 'Speed limiting point',
'SLW': 'Slow',
'SMC': 'Surface movement control',
'SMR': 'Surface movement radar',
'SNOCLO': 'Indicator for the aerodrome being closed due to snow on the runway (used in the METAR/SPECI code forms)',
'SNOWTAM': 'A special series NOTAM notifying the presence or removal of hazardous conditions due to snow, ice, slush or standing water associated with snow, slush and ice on the movement area, by means of a specific format.',
'SOT': 'Start of take-off run available',
'SPECIAL': 'Special meteorological report (in abbreviated plain language)',
'SPOC': 'SAR point of contact',
'SPOT': 'Spot wind',
'SR': 'Sunrise',
'SRA': 'Surveillance radar approach',
'SRC': 'Standard Route Clearance',
'SRE': 'Surveillance radar element of a precision approach radar system',
'SRG': 'Short range',
'SRR': 'Search and rescue region',
'SRY': 'Secondary',
'SSB': 'Single sideband',
'SSE': 'South south-east',
'SSR': 'Secondary surveillance radar',
'SST': 'Supersonic transport',
'SSW': 'South south-west',
'STA': 'Straight-in approach',
'STAR': 'Standard instrument arrival',
'STD': 'Standard',
'STF': 'Stratiform',
'STN': 'Station',
'STNR': 'Stationary',
'STOL': 'Short take-off and landing',
'STS': 'Status',
'STWL': 'Stopway light(s)',
'SUA': 'Special Use Airspace',
'SUBJ': 'Subject to',
'SUN': 'Sunday',
'SUP': 'Supplement (AIP Supplement)',
'SUPPS': 'Regional supplementary procedures',
'SVC': 'Service message',
'SVCBL': 'Serviceable',
'SVFR': 'Special visual flight rules',
'SW': 'South-west',
'SWB': 'South-westbound',
'SWY': 'Stopway',
'T-VASIS': '"T" visual approach slope indicator system (pronounced "TEE-VASIS")',
'TA': 'Transition altitude',
'TACAN': 'UHF tactical air navigation aid',
'TAIC': 'Transport Accident Investigation Commission',
'TAIL': 'Tailwind',
'TALO': 'Touchdown and lift-off area (located at a heliport)',
'TAR': 'Terminal area surveillance radar',
'TAS': 'True air speed',
'TAX': 'Taxiing or Taxi',
'TBA': 'To be advised',
'TCAD': 'Traffic alert and collision avoidance device',
'TCAS': 'Traffic alert and collision avoidance system',
'TCH':  'Threshold crossing height - ILS, PRA, PAPI and VASIS glide path (measured in feet above runway threshold)',
'TDO': 'Tornado',
'TDZ': 'Touchdown zone',
'TDZE': 'Touchdown zone elevation',
'TECR': 'Technical reason',
'TEL': 'Telephone',
'TEMPO': 'Temporary or Temporarily',
'TFC': 'Traffic',
'TGL': 'Touch-and-go landing',
'TGS': 'Taxiing guidance system',
'THR': 'Threshold',
'THRU': 'Through',
'THU': 'Thursday',
'TIBA': 'Traffic information broadcast by aircraft',
'TIL': 'Until',
'TIP': 'Until past ... (place)',
'TKOF': 'Take-off',
'TL...':  'Till (followed by the time by which weather change is forecast to end)',
'TL': 'Till',
'TLOF': 'Touchdown and lift-off area',
'TM': 'Transponder mandatory (used after text listing of airspace)',
'TN': 'Indicator for minimum temperature (used in the TAF code form)',
'TNA': 'Turn altitude',
'TNH': 'Turn height',
'TO': 'To ... (place)',
'TOC': 'Top of climb',
'TOD': 'Top of descent',
'TODA': 'Take-off distance available',
'TODAH': 'Take-off distance available, helicopter',
'TOP': 'Cloud top',
'TORA': 'Take-off run available',
'TP': 'Turning point',
'TR': 'Track',
'TRA': 'Temporary reserved airspace',
'TRANS': 'Transmits or Transmitter',
'TREND': 'Trend forecast',
'TRL': 'Transition level',
'TROP': 'Tropopause',
'TSO': 'Technical standard order',
'TT': 'Teletypewriter',
'TUE': 'Tuesday',
'TVOR': 'Terminal VOR',
'TWR': 'Aerodrome control tower or Aerodrome control',
'TWY': 'Taxiway',
'TWYL': 'Taxiway-link',
'TX': 'Indicator for maximum temperature (used in the TAF code form)',
'TYP': 'Type of aircraft',
'TYPH': 'Typhoon',
'U': 'Upward (tendency in RVR during previous 10 minutes)',
'U/S': 'Unserviceable',
'UAB': 'Until advised by...',
'UAC': 'Upper area control centre',
'UAR': 'Upper air route',
'UAS': 'Unmanned aircraft system',
'UAV': 'Unmanned aerial vehicle',
'UDF': 'Ultra high frequency direction-finding station',
'UFN': 'Until further notice',
'UHDT': 'Unable higher due traffic',
'UHF': 'Ultra high frequency [300 to 3 000 MHz]',
'UIC': 'Upper information centre',
'UIR': 'Upper flight information region',
'UL': 'Upper limit(s)',
'ULR': 'Ultra long range',
'UNA': 'Unable',
'UNAP': 'Unable to approve',
'UNICOM': 'Universal Communication Service',
'UNL': 'Unlimited',
'UNREL': 'Unreliable',
'UTC': 'Co-ordinated universal time',
'V': 'Indicator for variations from the mean wind direction (used in the METAR/SPECI code forms)',
'VAAC': 'Volcanic ash advisory centre',
'VAC': 'Visual approach chart',
'VAL': 'In valleys',
'VAN': 'Runway control van',
'VAR': 'Magnetic variation',
'VASIS': 'Visual approach slope indicator system',
'VDF': 'VHF direction-finding station',
'VER': 'Vertical',
'VFR': 'Visual flight rules',
'VHF': 'Very high frequency [30 to 300 MHz]',
'VHZ': 'Volcanic hazard zone',
'VIP': 'Very important person',
'VLF': 'Very low frequency [3 to 30 kHz]',
'VLR': 'Very long range',
'VNAV': 'Vertical navigation',
'VNC': 'Visual navigation chart',
'VOLMET':  'Meteorological information for aircraft in flight',
'VOR': 'VHF Omni-directional radio range',
'VORSEC': 'VOR/DME Minimum Sector Altitude Chart',
'VORTAC': 'VOR and TACAN combination',
'VOT': 'VOR airborne equipment test facility',
'VPA': 'Vertical path angle',
'VPC': 'Visual planning chart',
'VRP': 'Visual reporting point',
'VSA': 'By visual reference to the ground',
'VSM': 'Vertical separation minimum',
'VSP': 'Vertical speed',
'VSS': 'Visual segment surface',
'VTOL': 'Vertical take-off and landing',
'W': 'White',
'WAC': 'World Aeronautical Chart - ICAO 1:1 000 000 (followed by name/title)',
'WAFC': 'World area forecast centre',
'WAFS': 'World area forecast system - ICAO',
'WB': 'Westbound',
'WBAR': 'Wing bar lights',
'WDI': 'Wind direction indicator',
'WED': 'Wednesday',
'WEF': 'With effect from or effective from',
'WO': 'Without',
'WPT': 'Way-point',
'WRNG': 'Warning',
'WSPD': 'Wind speed',
'WSW': 'West south-west',
'WT': 'Weight',
'WTSPT': 'Waterspout',
'WWW': 'Worldwide web',
'X': 'Cross',
'XBAR': 'Crossbar (of approach lighting system)',
'XNG': 'Crossing',
'XS': 'Atmospherics',
'Y': 'Yellow',
'YCZ': 'Yellow caution zone (runway lighting)',
'YR': 'Your',
'Z': 'Coordinated universal time',
'NZWT': 'WHITIANGA',
'NZAA': 'AUCKLAND',
'NZAR': 'ARDMORE',
'NZTH': 'THAMES',
'NZME': 'MERCER',
'NZPU': 'PUKEKOHE',
'NZTG': 'TAURANGA',
'NZTE': 'TE KOWHAI',
'NZHN': 'HAMILTON',
'NZRO': 'ROTORUA',
  'WRITE THE ABBREVIATION HERE IN ALL CAPS': 'Here is an explanation of what it means',
};

let textareaRead = document.querySelector('.js-textarea-read');
let textareaWrite = document.querySelector('.js-textarea-write');
let buttonDecode = document.querySelector('.button-decode');
let buttonClear = document.querySelector('.button-clear');
buttonDecode.onclick = function () {
  const abbreviation = textareaRead.value.toUpperCase();
  const list = lists[abbreviation] || testFunction();
  let list_data = '';
  for (let key in list) {
    list_data += `${list[key]}`;
    textareaWrite.innerHTML = list_data;
    textareaWrite.classList.remove('red');

  }
}
function testFunction() {
  textareaWrite.innerHTML = 'No result available for this code, Please double check your spelling and try again.'; 
  textareaWrite.classList.add('red');
}
buttonClear.onclick = function () {
  textareaWrite.innerHTML = '';
  textareaRead.value = '';
}
function checkForEnter(e) {
  if (e.keyCode == 13) {
    event.preventDefault();
    buttonDecode.click();
  } else if ((e.keyCode == 8) || (e.keyCode == 46)) {
    textareaWrite.innerHTML = '';
  }

}
